<template>
<div>
  <b-overlay 
    :show="useAutoGeneratedLocation && !Object.keys(currentWeatherForecast).length" 
    spinner-variant="primary"
    spinner-type="grow"
    spinner-large
    rounded="sm"
  >
  <b-card v-if="useAutoGeneratedLocation && !Object.keys(currentWeatherForecast).length" title="Loading Current Weather">
  </b-card>
  </b-overlay>
    <b-card v-if="Object.keys(currentWeatherForecast).length" title="Current Weather" :sub-title="cityStateLocation ? cityStateLocation.city + ', ' + cityStateLocation.principalSubdivision : null">
          <b-jumbotron bg-variant="info" text-variant="white" :header="currentWeatherForecast.weather[0].main">
            <b-row>
              <b-col>
                <p>{{ currentWeatherForecast.weather[0].description }}</p>
                <b-img-lazy :src='urls.weatherForecastIconURL(currentWeatherForecast.weather[0].icon)' fluid alt="Fluid image"></b-img-lazy>
              </b-col>
              <b-col>
                <p>Current Temperature: {{ currentWeatherForecast.main.temp }}</p>
                <p>Feels Like: {{ currentWeatherForecast.main.feels_like }}</p>
                <p>Today's Lowest Temperature: {{ currentWeatherForecast.main.temp_min }}</p>
                <p>Today's Highest Temperature: {{ currentWeatherForecast.main.temp_max }}</p>
                <p>Humidity: {{ currentWeatherForecast.main.humidity }}%</p>
                <p>Pressure: {{ currentWeatherForecast.main.pressure }}</p>
              </b-col>
            </b-row>
          </b-jumbotron>
    </b-card>
    <div v-if="!useAutoGeneratedLocation && !Object.keys(currentWeatherForecast).length">
      <b-jumbotron 
        header="Search a location to see current weather forecast" 
        lead="The app was not able to find your location"
        bg-variant="warning"
      >
      </b-jumbotron>
    </div>
</div>
</template>

<script>
import { mapGetters, mapActions, mapState } from "vuex";

export default {
   name: 'CurrentTemperature',
   computed: {
    ...mapState('weatherForecast', ['urls']),
    ...mapGetters('weatherForecast', ['currentWeatherForecast']),
    ...mapGetters(['useAutoGeneratedLocation', 'cityStateLocation']),
   }, 
   methods: {
    ...mapActions('weatherForecast', ['getCurrentWeatherForecast'])
   } 
}
</script>