<template>
<div>
  <b-overlay :show="useAutoGeneratedLocation && !Object.keys(currentWeatherForecast).length" rounded="sm">
    <b-card title="Current Weather" :sub-title="cityStateLocation ? cityStateLocation.city + ', ' + cityStateLocation.principalSubdivision : null">
      <b-row>
        <b-col>
          {{ currentWeatherForecast.weather }}
        </b-col>
        <b-col>
          {{ currentWeatherForecast.main }}
        </b-col>
      </b-row>
    </b-card>
  </b-overlay>
</div>
</template>

<script>
import { mapGetters, mapActions } from "vuex";

export default {
   name: 'CurrentTemperature',
   computed: {
    ...mapGetters('weatherForecast', ['currentWeatherForecast']),
    ...mapGetters(['useAutoGeneratedLocation', 'cityStateLocation']),
   }, 
   methods: {
    ...mapActions('weatherForecast', ['getCurrentWeatherForecast'])
   } 
}
</script>