<template>
  <div>
    <b-card v-if="useAutoGeneratedLocation && !Object.keys(fiveDayWeatherForecast).length" title="Loading 5 Day Forecast">
      <b-overlay :show="useAutoGeneratedLocation && !Object.keys(fiveDayWeatherForecast).length" rounded="sm"></b-overlay>
    </b-card>
    <b-card title="5 Day Forecast" :sub-title="cityStateLocation ? cityStateLocation.city + ', ' + cityStateLocation.principalSubdivision : null">
      <b-card-group deck>
        <b-card v-if="weekdays.Monday" title="Monday" :sub-title="weekdays.Monday.date"> -->
          <weekday-weather-card :weekdayWeather="weekdays.Monday" />
        </b-card>
        <b-card v-if="weekdays.Tuesday" title="Tuesday" :sub-title="weekdays.Tuesday.date">
          <weekday-weather-card :weekdayWeather="weekdays.Tuesday" />
        </b-card>
        <b-card v-if="weekdays.Wednesday" title="Wednesday" :sub-title="weekdays.Wednesday.date">
          <weekday-weather-card :weekdayWeather="weekdays.Wednesday" />
        </b-card>
        <b-card v-if="weekdays.Thursday" title="Thursday" :sub-title="weekdays.Thursday.date">
          <weekday-weather-card :weekdayWeather="weekdays.Thursday" />
        </b-card>
      </b-card-group>
      <b-card-group deck>
        <b-card v-if="weekdays.Friday" title="Friday" :sub-title="weekdays.Friday.date">
          <weekday-weather-card :weekdayWeather="weekdays.Friday" />
        </b-card>
        <b-card v-if="weekdays.Saturday" title="Saturday" :sub-title="weekdays.Saturday.date">
          <weekday-weather-card :weekdayWeather="weekdays.Saturday" />
        </b-card>
        <b-card v-if="weekdays.Sunday" title="Sunday" :sub-title="weekdays.Sunday.date">
          <weekday-weather-card :weekdayWeather="weekdays.Sunday" />
        </b-card>
      </b-card-group>
    </b-card>
  </div>
</template>

<script>
import moment from 'moment'; 
import { mapGetters, mapActions } from "vuex";
import WeekdayWeatherCard from './WeekdayWeatherCard.vue'

export default {
    name: 'FiveDayTemperatures',
    data() {
      return {
        dayLookupTable: {
          1: 'Monday',
          2: 'Tuesday',
          3: 'Wednesday',
          4: 'Thursday',
          5: 'Friday',
          6: 'Saturday',
          7: 'Sunday'
        },
        uniqueTimes: []
      }
    },
    components: {
      WeekdayWeatherCard
    },
    methods: {
      ...mapActions('weatherForecast', ['getFiveDayWeatherForecast'])
    },
    computed: {
      ...mapGetters('weatherForecast', ['fiveDayWeatherForecast']),
      ...mapGetters(['useAutoGeneratedLocation', 'cityStateLocation']),
      weekdays() {
        const data = {};
        this.fiveDayWeatherForecast.map(day => {
          // const dateString  = day.dt_txt.split(' ')[0];
          // console.log(dateString)
          // this.uniqueTimes.indexOf(dateString.split(' ')[0]) === -1 ? this.uniqueTimes.push(dateString) : null
          const convertTime = new Date(day.dt_txt);
          const getDay = convertTime.getDay();
          const mapDayToLabel = this.dayLookupTable[getDay]
          if (!data[mapDayToLabel]) { 
            data[mapDayToLabel] = {
              'date': null,
              'weatherData': []
            }; 
          } else {
            data[mapDayToLabel]['date'] = moment(day.dt_txt).format('MMMM Do YYYY')
            data[mapDayToLabel]['weatherData'].push(day) 
          }
        });
        return data
      }
    }
}
</script>