<template>
  <div>
    <b-overlay 
      :show="useAutoGeneratedLocation && !Object.keys(fiveDayWeatherForecast).length" 
      spinner-variant="primary"
      spinner-type="grow"
      spinner-large
      rounded="sm"
    >
      <b-card v-if="useAutoGeneratedLocation && !Object.keys(fiveDayWeatherForecast).length" title="Loading 5 Day Forecast">
      </b-card>
    </b-overlay>
    <b-card v-if="Object.keys(fiveDayWeatherForecast).length" title="5 Day Forecast" :sub-title="cityStateLocation ? cityStateLocation.city + ', ' + cityStateLocation.principalSubdivision : null">
      <div v-for="(day, index) in sortedWeekdays" :key="index">
        <b-card v-if="day.weatherData.length" :title="day.label" :sub-title="day.date" style="max-height: 70%">
          <weekday-weather-card :weekdayWeather="weekdays.Monday" />
        </b-card>
      </div>
    </b-card>
    <div v-if="!useAutoGeneratedLocation && !Object.keys(fiveDayWeatherForecast).length">
      <b-jumbotron 
        header="Search a location to see the five day weather forecast" 
        lead="The app was not able to find your location"
        bg-variant="warning"
      >
      </b-jumbotron>
    </div>
  </div>
</template>

<script>
import moment from 'moment'; 
import { mapGetters, mapActions } from "vuex";
import WeekdayWeatherCard from './WeekdayWeatherCard.vue'

export default {
    name: 'FiveDayTemperatures',
    data() {
      return {
        dayLookupTable: {
          0: 'Sunday',
          1: 'Monday',
          2: 'Tuesday',
          3: 'Wednesday',
          4: 'Thursday',
          5: 'Friday',
          6: 'Saturday'
        },
        uniqueTimes: []
      }
    },
    components: {
      WeekdayWeatherCard
    },
    methods: {
      ...mapActions('weatherForecast', ['getFiveDayWeatherForecast'])
    },
    computed: {
      ...mapGetters('weatherForecast', ['fiveDayWeatherForecast']),
      ...mapGetters(['useAutoGeneratedLocation', 'cityStateLocation']),
      weekdays() {
        const data = {};
        this.fiveDayWeatherForecast.map(day => {
          const convertTime = new Date(day.dt_txt);
          const getDay = convertTime.getDay();
          const mapDayToLabel = this.dayLookupTable[getDay]
          if (!data[mapDayToLabel]) { 
            data[mapDayToLabel] = {
              'label': mapDayToLabel,
              'date': null,
              'weatherData': []
            }; 
          } else {
            data[mapDayToLabel]['label'] = mapDayToLabel;
            data[mapDayToLabel]['date'] = moment(day.dt_txt).format('MMMM Do YYYY');
            data[mapDayToLabel]['weatherData'].push(day);
          }
        });
        return data
      },
      sortedWeekdays() {
        return Object.values(this.weekdays).sort((a, b) => (a.date > b.date) ? 1 : -1)
      }
    }
}
</script>