<template>
  <div>
    <!-- <b-overlay :show="useAutoGeneratedLocation && !Object.keys(fiveDayWeatherForecast).length" rounded="sm"> -->
    <b-card title="Five Day Weather Forecast" :sub-title="cityStateLocation ? cityStateLocation.city + ', ' + cityStateLocation.principalSubdivision : null">
    </b-card>
    {{ fiveDayWeatherForecast }}
    <!-- </b-overlay> -->
  </div>
</template>

<script>
import { mapGetters, mapActions } from "vuex";

export default {
    name: 'FiveDayTemperatures',
    data() {
      return {
        weekdays: {

        }
      }
    },
    methods: {
      ...mapActions('weatherForecast', ['getFiveDayWeatherForecast'])
    },
    computed: {
      ...mapGetters('weatherForecast', ['fiveDayWeatherForecast']),
      ...mapGetters(['useAutoGeneratedLocation', 'cityStateLocation'])
    }
}
</script>